from . import ma
from marshmallow import fields

class CustomerSchema(ma.Schema):
    id = fields.Integer(required=False) #Primary Key is Autogenerated and doesn't need to be apart of the payload
    name = fields.String(required=True)
    email = fields.Email(required=True)
    phone = fields.String(required=True)
    username = fields.String(required=True)
    password = fields.String(required=True)
    role_id = fields.Int(missing=1)  # Use missing to set default for deserialization

    class Meta: 
        fields = ("id", "name", "email", "phone", "username", "password")

class CustomerOrderSchema(ma.Schema):
    name = fields.String(required=True)
    email = fields.Email(required= True)

class CustomerUpdateSchema(ma.Schema):
    name = fields.String(required=True)
    email = fields.Email(required= True)
    phone = fields.String(required=True)

class CustomerDeleteSchema(ma.Schema):
    id = fields.Integer(required=False)
    name = fields.String(required=False)
    email = fields.Email(required=False)
    phone = fields.String(required=False)
    username = fields.String(required=False)
    password = fields.String(required=False)
    
customer_schema = CustomerSchema()
customers_schema = CustomerSchema(many=True, exclude=["password"])
customer_update_schema = CustomerUpdateSchema()
customer_delete_schema = CustomerDeleteSchema()

